### ISSUE TITLE
Error when used inside Grid field

### ISSUE THREAD

**Issue by andyra** [goellner/statamic-assets-organized#6]
When using Assets Organized inside a grid field instance, I get the following error:

```
Uncaught (in promise) TypeError: Cannot read property 'assets' of undefined
    at AssetsOrganizedFieldtype.ready (fieldtype.js:57)
```

My field definition looks like this:

```
audio_file:
  type: assets_organized
  container: s3
  folder: albums
```

If I use that same field definition outside the Grid field, it works as expected.

Using AssetsOrganized v1.2.0 with Statamic 2.11.9
